export enum GamePhase {
  EXPLORING = 'EXPLORING',
  SHOWING_DECISION = 'SHOWING_DECISION',
  AWAITING_REASONING = 'AWAITING_REASONING',
  WAITING_FOR_AI = 'WAITING_FOR_AI',
  SHOWING_CHALLENGE = 'SHOWING_CHALLENGE',
  SHOWING_EVALUATION = 'SHOWING_EVALUATION',
}
