export enum GamePhase {
  MENU = 'MENU',
  GATE_INPUT = 'GATE_INPUT',
  WAITING_FOR_QUESTION = 'WAITING_FOR_QUESTION',
  EXPLORING_DOORS = 'EXPLORING_DOORS',
  DOOR_CONTEXT = 'DOOR_CONTEXT',
  TROPHY = 'TROPHY',
  TRAVERSING_OPTION = 'TRAVERSING_OPTION',
  CORRIDOR_PROCESSING = 'CORRIDOR_PROCESSING',
  WORKSTATION = 'WORKSTATION',
}